// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG4T_3gxAk-yQwSnRQYVMkQ6SB-jlTuR4',
    appId: '1:38602606359:web:7b137fb5e3a878a42f1952',
    messagingSenderId: '38602606359',
    projectId: 'news-ac52a',
    authDomain: 'news-ac52a.firebaseapp.com',
    storageBucket: 'news-ac52a.appspot.com',
    measurementId: 'G-SBMP8MDNJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtJ9_Kq2rKpT4SQ9XvyvpJzwgYeUeOAi0',
    appId: '1:38602606359:android:4996637d90e998c22f1952',
    messagingSenderId: '38602606359',
    projectId: 'news-ac52a',
    storageBucket: 'news-ac52a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdznMeawmaGpQA2KksxYAUQXAunGHo7O8',
    appId: '1:38602606359:ios:41dd77a09e431a652f1952',
    messagingSenderId: '38602606359',
    projectId: 'news-ac52a',
    storageBucket: 'news-ac52a.appspot.com',
    iosBundleId: 'com.example.socoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdznMeawmaGpQA2KksxYAUQXAunGHo7O8',
    appId: '1:38602606359:ios:41dd77a09e431a652f1952',
    messagingSenderId: '38602606359',
    projectId: 'news-ac52a',
    storageBucket: 'news-ac52a.appspot.com',
    iosBundleId: 'com.example.socoproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG4T_3gxAk-yQwSnRQYVMkQ6SB-jlTuR4',
    appId: '1:38602606359:web:68fadf2cf829bcc42f1952',
    messagingSenderId: '38602606359',
    projectId: 'news-ac52a',
    authDomain: 'news-ac52a.firebaseapp.com',
    storageBucket: 'news-ac52a.appspot.com',
    measurementId: 'G-BYQ4KT044B',
  );
}
